//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Глазки_SaveErshov.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Password { get; set; }
        public string photo { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
