//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgencyErshov.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers_
    {
        public int EmpID { get; set; }
        public byte[] Photo { get; set; }
        public string ServiceType { get; set; }
        public string FIO { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string LastLogIn { get; set; }
        public string LoginType { get; set; }
    
        public virtual LoginLog LoginLog { get; set; }
    }
}
