//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlagodatErshov.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Barcodes = new HashSet<Barcodes>();
            this.Services_ = new HashSet<Services_>();
        }
    
        public int OrderID { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int ClientID { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string RentTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Barcodes> Barcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services_> Services_ { get; set; }
    }
}
