//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgencyErshov.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int TourID { get; set; }
        public string TourName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> TicketsCount { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> IsActual { get; set; }
        public Nullable<int> TourTypeID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual TourType TourType { get; set; }
    }
}
